name: "Terraform GitHub Actions"
on:
  - push
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: init
        id: init
        run: terraform init -backend-config="token=${{ secrets.TF_API_TOKEN }}"
      - name: plan
        id: plan
        run: terraform plan -no-color -backend-config="token=${{ secrets.TF_API_TOKEN }}"
        continue-on-error: true
    #   - name: "Terraform Init"
    #     uses: hashicorp/setup-terraform@v3
    #     with:
    #       tf_actions_subcommand: "init"
    #       tf_actions_working_dir: "."
    #       tf_actions_comment: true
    #       args: '" -backend-config="organization=salimon"'
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
